### ISSUE TITLE
Remove privacy of this repository

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/tag#11]
This repository is currently private and needs to be open.
[The charter on the current TDWG site](http://www.tdwg.org/activities/tag/charter) is outdated and people need to be able to see the current charter, especially in light of the upcoming elections.

**Comment by hlapp** [comment]
@ghwhitbread you can see from whom the votes came by hovering your mouse over the reactions.

**Comment by ghwhitbread** [comment]
thanks @hlapp - found that (hover not so good on tablet).  3 is good enough.  
Note that every member of @tdwg/tag-team has admin rights on this repository. 
I will leave for @timrobertson100 to close.

**Comment by peterdesmet** [comment]
Repo is private so i’ll close this.

**Comment by peterdesmet** [comment]
Correction: repo is now **public**
