### ISSUE TITLE
With the Process IG create an overview of the TDWG landscape

### ISSUE THREAD

**Issue by chicoreus** [tdwg/tag#16]
TAG and Process IG have been tasked by the executive with creating a knowlege-graph and overview of the TDWG activities and standards landscape.

Notes on this issue from the TAG meetings at TDWG 2017 are: "TAG and Process should begin with a road-map document (with graphic representations) showing relationships among TDWG IG/TGs as well as a graph depicting the view from each IG/TG.  Each IG/TG should validate/revise the IG/TG centered view of the TDWG landscape."  Also see the discussion notes, particularly from near the end of the Thursday meeting.

**Comment by baskaufs** [comment]
There has been no progress on this and seems to be little interest in moving it forward. I've combined this with some other issues when creating https://github.com/tdwg/tag/issues/37
