### ISSUE TITLE
Review GGBN standard

### ISSUE THREAD

**Issue by chicoreus** [tdwg/tag#17]
Members of the Arctos and Specify projects who are attempting to provide data to GGBN are seeing significant issues in use of dwc:Occurrence and dwc:MaterialSample in mapping and providing data to GGBN.  The TAG needs to look closely at the currently in review GGBN standard to evaluate interoperability issues with existing TDWG standards, particularly DarwinCore.

**Comment by pmergen** [comment]
Indeed I was in the session, it was unclear if they are unaware of the Sample base option of Darwin Core that may be worth to test, or if they have tested it and have reservations. 
ABDCDNA can handle apparently some of those issues. It was quite interesting and I think the Arctos and Specify speakers and their networks can be very interesting to bring into our review process ...

**Comment by tucotuco** [comment]
I caan represent the Arctos perspective. I have been helping them in their
attempts to publish to GGBN. What Teresa Mayfield presented explains all
the issues encountered in trying to prepare data for GGBN, ultimately
neccesarily requiring a separate IPT resource (for samples) from that to
publish to GBIF (for Occurrences).
GGBN did explore the MatetialSample core, but opted not to use it, stating
that it was the same schema as the Occurrence Core (true), and that it was
not available to publish against in the IPT (also true).
I believe that it should be possible to publish a single Occurrence
resource with extensions that could satisfy both GBIF and GGBN. Indeed, I
think it is only reasonable to have that expectation.

**Comment by baskaufs** [comment]
The issue of moving the process of moving the GGBN standard forward as a TDWG standard was discussed repeatedly at TAG meetings between March and November 2022. During that period, we attempted without success to find a champion who could take administrative responsibility for moving the process forward. It was noted that failure to ratify GGBN as a TDWG standard would not prevent people from using it, as it is already a complete, independent standard that is in use. At the 2022-11-07 TAG working session, it was proposed and accepted without objection to close this issue with the understanding that if a champion arose who wanted to move the process of making GGBN a standard, we would be happy to assist (and document our task in a new issue).

**Comment by baskaufs** [comment]
Note that the @tdwg/exec was notified about this decision in their 2022-11-08 meeting by @baskaufs
