### ISSUE TITLE
Evaluate Interoperability of Collections in AC and (N)CD.

### ISSUE THREAD

**Issue by chicoreus** [tdwg/tag#18]
In the AC maintenance group meeting at TDWG 2018, it was noted that a point of contact between Audubon Core and the work in revisiting (Natural) Collections Description is the concept of a Collection - both scopes will contain terms describing the nature and scope of some form of Collection entity.  The TAG should monitor the work in (N)CD, and evaluate this potential point of overlap.

**Comment by baskaufs** [comment]
Given that the Latimer Core (a.k.a. Collections Description) draft standard has gone to a review manager, I think additional discussion of this can take place as part of the review process.
