### ISSUE TITLE
Deprecate TDWG LSID recommendation

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#2]
Update the TDWG GUID applicability standard documents at  https://github.com/tdwg/guid-as or retire GUID standard and replace with recommendations in TDWG web content
- [ ] Decide if to retire standard and move into web content ?
- [ ] #7 Revise https://github.com/tdwg/guid-as/blob/master/guid/applicability_statement.doc ?
- [ ] #8 Deprecate https://github.com/tdwg/guid-as/blob/master/lsid/applicability_statement.doc ?

**Comment by baskaufs** [comment]
This issue is being closed with further discussion to take place in https://github.com/tdwg/tag/issues/36 or other issues opened as necessary in the future.
