### ISSUE TITLE
Review standard statuses

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/tag#20]
There are currently [5 statuses for TDWG standards](https://www.tdwg.org/standards/status-and-categories/):

- **Current Standard**: Standards that TDWG recommends for use.
- **Current (2005) Standard**: Standards that TDWG recommends for use and were ratified by membership vote at the TDWG Annual Meeting 2005 in St. Petersburgh. These standards are not in the format of current TDWG standards, nor have they been submitted to both expert and public review, the ratification process adopted at the St Louis annual meeting in 2006.
- **Draft Standard**: Standard under review submitted to the TDWG Standards Track after 2006.
- **Prior Standard**: Standards that were ratified prior to 2005 and that are not currently being promoted for ratification under the post 2006 ratification process. These standards currently lack a 'champion' to bring them into line with the draft specification and submit them to the new standards development process adopted in St Louis in 2006.
- **Retired Standard**: Standards that have been ratified by TDWG in the past but that are no longer recommended. 

Especially the statuses `Current (2005)` and `Prior` are confusing, as they try to keep track of history, rather than being a clear status. We kinda keep track of history (and the fact that a standard might have gone through a different review process) with the publication/ratification date. We also have a bigger problem in not retiring old standards than not knowing the review differences between standards. It is therefore suggested in https://github.com/tdwg/website/pull/111 to simplify the statuses to:

- **Recommended standard** = current, current 2015 and prior
- **Draft standard**
- **Retired standard**: maybe including some of the prior

Can the @tag discuss/approve this soon? /cc @baskaufs

**Comment by baskaufs** [comment]
The standards categories should be considered along with a general review of our standards in https://github.com/tdwg/tag/issues/37
