### ISSUE TITLE
TDWG-wide policy on use of namespaces for ancillary vocabularies

### ISSUE THREAD

**Issue by baskaufs** [tdwg/tag#24]
I'm not sure what is on the agenda for the TAG meeting coming up in Leiden, but there are a couple issues I hope we can discuss.  By "discuss", I don't necessarily mean resolving them, but at least initiate some process to resolve them (establish task group, committee, etc.).  

The first issue is regarding the use of namespaces for vocabularies that are associated with other vocabularies such as Darwin Core and Audubon Core.  For example, there are controlled vocabularies being developed for both DwC and AC.  The Audubon Core Maintenance Group is also planning to create a number of class terms to be used as values for `ac:subtype`.  

It seems that there are three possible ways to handle this:

1. Include the new terms within the main namespace for the "parent" vocabulary.  For example, include them within `http://rs.tdwg.org/ac/terms/` for Audubon Core.
2. Create a new namespace URI located hierarchically below the base URI for the standard. For the AC subtypes example: `http://rs.tdwg.org/ac/subtypes/` .
3. Create an entirely new namespace URI within the rs.tdwg.org subdomain, e.g. `http://rs.tdwg.org/acsubtypes/terms/`

I'm not sure that there is a single answer to this question, since I think the answer may depend on whether its likely that the terms would be used exclusively with the "parent" vocabulary or if they may be used across other TDWG vocabularies as well.  For example, terms in the `http://rs.tdwg.org/dwc/terms/attributes/` namespace, which was originally intended for use with DwC, has been expanded by the Standards Documentation Specification for use across TDWG vocabularies (see Sections 4.1.2, 4.5, 4.5.3, etc. in the [SDS](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md)) as the `tdwgutility:` namespace.  So it would have been better to have not had its namespace URI nested hierarchically within DwC.

See also what's left of the [DwC Namespace Policy](https://dwc.tdwg.org/namespace/), which is the only official document that I can think of that has anything to say about use of namespaces (but doesn't answer this question).  The Audubon Core [notes (non-normative) for `ac:subtype`](https://tdwg.github.io/ac/termlist/#ac_subtype) say "Communities should define the URI in a namespace of their choosing or devising. For example, "http://my.inst.org/namespace/metadata/subtype/SlideShow")." but I'm not sure that's a great idea if we are trying to help users provide consistent values for terms.  The 3D imaging community is agitating right now for AC to mint a subtype for 3D media, but the Maintenance Group doesn't know how to proceed on the URI pattern.

I think the TAG should be proactive about this because the various efforts to create these ancillary vocabularies are chugging along and at some point, groups are going to want to start minting terms for them.

**Comment by tucotuco** [comment]
I agree it would be useful to have solid guidance on this front, as many more vocabularies are likely to be developed soon, especially within the BDQ Task Group 4 on vocabularies of values (https://www.tdwg.org/community/bdq/tg-4/). The topic is also pertinent for the creation of Darwin Core extensions, which often occur, for the sake of expediency, outside the TDWG standards process.

**Comment by baskaufs** [comment]
This issue has been settled by evolving practice. The namespaces in current use are as follows:

### Audubon Core
- `http://rs.tdwg.org/acvariant/values/` for controlled vocabulary for ac:variant
- `http://rs.tdwg.org/acsubtype/values/` for controlled vocabulary for ac:subtype
- `http://rs.tdwg.org/format/values/` for controlled vocabulary for dc:format

### Darwin Core
-`http://rs.tdwg.org/dwcem/values/` for controlled vocabulary for dwc:establishmentMeans
-`http://rs.tdwg.org/dwcdoe/values/` for controlled vocabulary for dwc:degreeOfEstablishment
-`http://rs.tdwg.org/dwcpw/values/` for controlled vocabulary for dwc:pathway
-`http://rs.tdwg.org/chrono/terms/` for the Chronometric Age extension to Darwin Core

The vocabulary is identified in the first level of the path, with "terms" or "values" at the second level. First path levels are prepended with "ac" or "dwc" if they are exclusively used within the parent standard and not if they might have broader application (e.g. dc:format and the Chrono extension).
