### ISSUE TITLE
TDWG-wide policy on opacity of identifiers for controlled vocabulary terms

### ISSUE THREAD

**Issue by baskaufs** [tdwg/tag#25]
Here is a second issue that I would like to see discussed at the TAG meeting in Leiden if possible.

As I mentioned in Issue #24, there are task groups and other groups who have made significant progress on creating controlled vocabularies to be used with Darwin Core and Audubon Core terms.  At some point in the near future, they are going to be making official term proposals, and somebody is going to have to figure out what term IRIs should be assigned to the new controlled vocabulary terms.  

Historically, vocabularies like DwC and AC have followed the practice of Dublin Core and used local names (i.e. the part of the URI after the namespace) that are derived from English labels.  This has led to endless confusion among "term names", labels, controlled values, etc. and what values should be used for each of these.  The [Standards Documentation Specification](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md) (SDS) straightens this out in section 3.3.3.1 by distinguishing between the term name (e.g. 'dwc:recordedBy'), the English language label (e.g. "Recorded By"), and the controlled value string (not applicable to any existing TDWG terms since we don't have any ratified controlled vocabularies yet).  

One way to get rid of this confusion would be to use opaque (e.g. numeric) identifiers as the local names for controlled vocabulary terms.  This would have the benefit of clearly differentiating between the local name of the URI, labels in various languages, and the controlled value string that we want people to use in spreadsheets.  As an example from the dwc:establishmentMeans controlled vocabulary that Quentin Groom et al. are working on, we could have a term with this:

URI= http://rs.tdwg.org/dwc/em/321
label="native: reintroduced"
controlled value string="nativeReintroduced"

The negatives of this would be that it departs from previous precedent. Also based on the way that the SDS defines "term name" the term name would be something like `dwcem:321`, which isn't what people usually think of as a "name".

Anyway, it would be good to be proactive and have a TDWG-wide policy on this prior to the submission of controlled vocabularies as new standards since we don't want to hold up the ratification process by a year while people bumble around trying to figure out how to handle this issue.

**Comment by tucotuco** [comment]
I support this initiative. It would be good to have a formal policy before
we go much further. In my opinion, following Dublin Core for Darwin Core
made good sense and has not caused any calamities as far as I can tell,
neither with Dublin Core nor with Darwin Core. The most tangible negative
practical impact I have seen is in the IPT using the Audubon Media
Description extension. Because Audubon Core has pairs of terms with the
same unqualified name and distinct iris, and because the IPT only uses the
unqualified name to try to make an automatic mapping, the pairs of terms
get mapped to the same input field. There is great potential for this to
happen with Darwin Core as well, where the classic namespace (
http://rs.tdwg.org/dwc/terms alias dwc:) and the Darwin Core as RDF-minted
namespace (http://rs.tdwg.org/dwc/iri/ alias dwciri:) have unqualified term
names in common by design.
In the ontology world opaque identifiers don't seem to cause any problems
either, but I posit that is because the community and tools have been built
up around that expectation. Unlike in the ontologies, our community grew up
thinking of the labels as field names, and the official term IRIs as the
fully expanded version of that. They give us a sense of comfort that we
have the right term that a number can not, even if it might be confusing
when to use qualified names, unqualified names, preferred labels in a given
language.

**Comment by qgroom** [comment]
Hi Steve and John,
as you can imagine I'm enthusiastic about getting this resolved.
I suspect that opaque identifiers will be a big pill for the community to swallow, but it might be better in the long run. Also, I think the biggest hurdle would be getting people to use identifiers at all, not the choice of identifiers.

**Comment by debpaul** [comment]
To @qgroom's excellent point "...Also, I think the biggest hurdle would be getting people to use identifiers at all, not the choice of identifiers." 

Consider, whatever we choose, to look at the current software in place (from the IPT, to ARCTOS, Symbiota, Specify, EMu, etc). What kind of changes are needed in these data mgmt tools to support collections staff implementing these controlled vocabs?

Do we imagine a dropdown in the software that would say

> nativeReintroduced

but in the resulting DwC-A file exported, the term would be shared using the dwciri instead?
>dwciri:http://rs.tdwg.org/dwc/em/321

(and a side note/question? it's been mentioned before, the need for the "version" of DwC being used to be carried in the URIs. Does this URI http://rs.tdwg.org/dwc/em/321 carry version information)?

**Comment by baskaufs** [comment]
The whole point of labels is that they are what is displayed to end users who should not be subjected to the painful IRIs.  If we are doing our jobs, we will develop sets of labels other than the required English ones to make it possible for users in any country to interact with software we develop.  So no, the dropdown should not say "nativeReintroduced".  It should work like this: http://bioimages.vanderbilt.edu/pick-list.html and regardless of the language shown to the user, the software should record the language-independent IRI.

If our software does not work like this, then we should fix it so that it does.  No excuses, we are an international organization.  The controlled value string is only a concession for people who have to use spreadsheets and need to have something consistent to paste directly into a cell.

**Comment by debpaul** [comment]
Hi @baskaufs - nicely put - and thanks for the link to how the picklist should work. My point is that while it "should" work as you have shown/described, some collection mgmt software does need updating, and not only for these controlled vocabularies. We'll need to partner with our major software providers -- and the sooner we have discussions with them the better.

**Comment by WUlate** [comment]
Hello,
As anyone having worked with multiple providers with diverse platforms in different languages, I see (and long) for the benefit of this standardization, so I support having TDWG develop an organization-wide policy on opacity of identifiers for controlled vocabulary terms; but, knowing my crowd, I'm also worried about the size of the pill.
  
Is there a transition path we could adopt?  Something like recommending, from now and until the moment all software is working as it should, that users employ redundant information in the files/spreadsheets/DBs: the term names and the labels, the IRIs and the controlled value strings and promote fully qualified values as a concession for clarity?

**Comment by timrobertson100** [comment]
Can you summarise the motivation for using numeric identifiers please @baskaufs? (language-neutral, avoid fixing an original label?). I'm sure there is agreement that software should be multi-lingual but the [example above](http://bioimages.vanderbilt.edu/pick-list.html) can be accomplished without opaque identifiers for example. 

I think we'd be wise to separate out data capture, transfer, and archival use cases. When it comes to archival, storing identifier references to concepts that may or may not be available in the future is not as robust as storing a value that can be deciphered reasonably. 

> The whole point of labels is that they are what is displayed to end users who should not be subjected to the painful IRIs.

I'd wager spreadsheets are the most commonly used format and where I'd propose we should make them as accessible as possible (i.e. not littered with identifiers to dereference).

Does this discussion cover terms as well please? E.g. does `dwc:establishmentMeans` become something like `dwcterm:1`

**Comment by baskaufs** [comment]
Just to clarify, I'm not suggesting that we change the way we are generating IRIs for property terms like `dwc:establishmentMeans` that are part of Darwin Core, Audubon Core, etc.  I'm only talking about controlled vocabulary terms that would be used as **values** for the property terms.  

There are two motivations.  One is as you said: language neutrality.  But the main thing in my mind is to avoid confusion between term local names, labels, and controlled value strings.  Previously these three things have been conflated.  But they should be distinct things.  

The controlled value strings are what are intended for the purpose you describe as common (spreadsheets).  Each controlled vocabulary term MUST (sensu RFC 2119) have one (see the last paragraph of Section 4.5.4 of the [Standards Documentation Specification](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md)) that is a plain text literal.  That is not any change from current practice with spreadsheets other than to get rid of the ambiguity of what people should use for that string.  

The advantage of establishing and using a controlled value term IRI is that it will be guaranteed to be globally unique (something not true about the controlled value string).  Therefore, it would be best for software developers to plan to use these IRIs as the actual stored value, rather than storing the controlled value strings.  In that scenario, an application that consumes spreadsheets would "look up" the controlled value string (e.g. "nativeReintroduced") and store the IRI (e.g. `http://rs.tdwg.org/dwc/em/321`).  If we do our job right, people shouldn't routinely have to use the opaque IRIs since they would either be putting the controlled value strings in a spreadsheet, or selecting a label in their own language from a picklist and software would be figuring out the IRI.

**Comment by baskaufs** [comment]
Also, there is no requirement that the IRIs even dereference.  In this context, they are simply globally unique identifiers that could be stored like any other string in a database.

**Comment by timrobertson100** [comment]
Thanks @baskaufs - thought-provoking discussion

> ...there is no requirement that the IRIs even dereference

I would **strongly** advise against anyone doing this. GBIF have done this in the past and it caused nothing but confusion for everybody who saw them with reports of things being broken. 

> ...it would be best for software developers to ... use these IRIs as the actual stored value

I think you might have overlooked my point on archival. When we're talking about storing data packages for >10 years (e.g. a DataCite contract) then we need to consider the likelihood that the dictionary service will no longer be available. 

> I'm not suggesting that we change the way we are generating IRIs for property terms

Is there a reason why not, as I presume the same justification would apply?

**Comment by tucotuco** [comment]
It seems to me too that the same justifications would apply to property
terms. That's partly why I would hesitate to do it.

**Comment by baskaufs** [comment]
@timrobertson100 , 

Well, the IRI dereferencing is a different issue.  I also agree that all TDWG-issued IRIs should dereference.  But to play devil's advocate, end users should not need to routinely see or deal with the IRIs if we do this right.  So they shouldn't have any reason to be casting about trying to dereference them.

I'm not sure what the issue is with a "dictionary service".  The whole point of having the controlled vocabularies be part of a standard is that it ensures that TDWG takes responsibility for keeping the term metadata available indefinitely.  That's one of the reasons why I'm keen on making sure that all historical term metadata are available as CSV files in the https://github.com/tdwg/rs.tdwg.org GitHub repo.  That's about as future-proof as I can imagine since plain text CSV files should be interpretable indefinitely, short of an asteroid strike and the end of civilization as we know it.  So you have a CSV row with the IRI in one column, the English label in a column, the controlled value string in a column, and the definition in another column.  Any programmer worth his or her salt should be able to write a script to do the reconciliation of IRI to any other bit of term metadata in less than 5 minutes.

One COULD apply the same justification to other vocabularies like Darwin Core and Audubon Core, but the difference there is that we have precedents for how we construct those IRIs.  We don't have precedents for controlled vocabularies.  So we have the luxury of thinking about what kind of precedent we want to set before we actually have to set it.   In my opinion, that's a pretty good position to be in.

**Comment by hlapp** [comment]
> Well, the IRI dereferencing is a different issue. I also agree that all TDWG-issued IRIs should dereference. But to play devil's advocate, end users should not need to routinely see or deal with the IRIs if we do this right. So they shouldn't have any reason to be casting about trying to dereference them.

For what it's worth, I find myself dereferencing UBERON and other OBO term and property IRIs all the time. It's the most convenient way pull up all kinds of information about the term (because most OBO ontologies have their term IRIs redirected to Ontobee if `text/html` is requested (such as through a browser), and it's the most direct way to either cite or link these terms in online threads.

Perhaps I'm not an end user in the sense you use the word, but if so, I'd argue it's then worth defining applicable personas and who (in terms of audience) you are talking about.

**Comment by baskaufs** [comment]
Well, the issue of IRI dereferencing is a separate issue from the one being discussed here and I think everyone who has expressed an opinion here agrees that having IRIs dereference is a best practice.  We should open a separate issue about IRI dereferencing if we want to talk about that more.

Since my previous comments on this issue, I thought of a good example of why there is a problem with people conflating human-readable labels (like "recorded by") with compact URIs (CURIES) like dwc:recordedBy.  As some of you may recall, Darwin Core had the term dwc:individualID, which was intended to provide a way to group repeated observations of the same individual organism.  After the decision to create the dwc:Organism class, it seemed like a good idea to replace dwc:individualID with dwc:organismID, a term to serve the same purpose.  The rational was that we had an IRI pattern where there was an "ID" term whose local name was similar to the local name of the class IRI for every defined class in Darwin Core.  However, in retrospect, I believe that the decision to replace dwc:individualID with dwc:organismID (which I supported at the time) was incorrect.  The correct course of action would have been to leave the IRI as dwc:individualID, but change the term label from "individual ID" to "organism ID".  That would not have "broken" any applications in the way that changing the term IRI did.

So why did that better course of action seem so unpalatable to us?  Because we were hung up on the idea that our identifiers should contain metadata (i.e. the label).  It would have freaked people out if we had a term with a CURIE of dwc:individualID and a label of "organism ID".  On the other hand, if we had an opaque identifier like dwc:347 and changed its label from "individual ID" to "organism ID", nobody would have cared and nothing would have been broken.

As I said before, I'm not suggesting that we change the current pattern for property term IRIs in Darwin Core and Audubon Core.  That precedent has worked relatively well for years.  However, we have an opportunity to set a different precedent for TDWG controlled vocabulary terms (using opaque local names for CURIES/IRIs) if we believe that opaque identifiers would be better.  It seems to me that we might be even more likely to change human-readable labels for controlled vocabulary terms than property terms, and that would argue for disentangling the CURIES from the labels.  

Please keep in mind that I'm talking about the term IRIs and NOT the controlled vocabulary strings that people will be using in spreadsheets.  Those should probably be related in some way to the labels so that the people putting them in the spreadsheets can remember what they are.  But like IRIs, they should remain unchanging and be unique (at least within the controlled vocabulary).

**Comment by jar398** [comment]
For reference, here is the OBO statement on term URIs: http://obofoundry.org/id-policy.html

My guess is that the decision to use integers instead of text for labels was based on long experience with text labels being "discovered" to be at odds with either intent or use in the wild, and/or labels whose natural-language or technical-language meaning has changed (through refinement, extension, metaphor, etc.) over time, as natural language tends to do, and/or the deployed uses of a URI changing over time.

This is related to the "metadata in URI" issue https://www.w3.org/2001/tag/doc/metaDataInURI-31.html , which is essentially about whether you "should" use label text as a clue to meaning.  If the label is a number, it's pretty hard to do this, thus satisfying the goal of forestalling incorrect interpretation by forcing the curious to seek information from secondary sources (such as a specification).

**Comment by baskaufs** [comment]
Regardless of the merits argued in this issue, the precedent has been established that identifiers that are SKOS Concepts have opaque identifiers. See http://rs.tdwg.org/dwc/doc/doe/ 
    http://rs.tdwg.org/dwc/doc/pw/ http://rs.tdwg.org/ac/doc/format/ etc.
