### ISSUE TITLE
Provide guidance to TDWG standards on cardinalities other than 1:1

### ISSUE THREAD

**Issue by chicoreus** [tdwg/tag#29]
@baskaufs  noted in the AC and CD IG meetings today that there is a pressing need for guidance from the TAG on how TDWG task groups should propose to represent relationships between data objects other than simple flat one to one relationships.  In the absence of guidance from the TAG, different groups are addressing this in different ways, indeed, work with in CD has been internally examining different approaches.

**Comment by baskaufs** [comment]
There has been discussion about this in the Audubon Core Maintenance Group (https://github.com/tdwg/ac/issues/225) relating to a possible revision of the [Audubon Core Structure document](https://ac.tdwg.org/structure/) and within Darwin Core related to the developing model for serializing complex data in a non-Occurrence-centric way. The TAG needs to track these developments to maintain consistency in approach among these existing standards as well as new ones that would be likely to follow their precedents.
