### ISSUE TITLE
TAG bimonthly meeting 27 June 2022

### ISSUE THREAD

**Issue by baskaufs** [tdwg/tag#32]
The next TDWG TAG bimonthly meeting will be at 13:00 UTC on Monday, 2022-06-27. That should correspond to:

8 AM Central daylight time (Chicago)
8 AM Columbia Time (Bogatá)
9 AM Eastern daylight time (New York/Ottawa)
10 AM Argentina Time (Buenos Aires)
2 PM British summer time (London)
3 PM Central European summer time (Berlin/Copenhagen)
3 PM South Africa standard time (Johannesburg)

For a calendar invitation and Zoom link, email [Steve Baskauf](mailto:steve.baskauf@vanderbilt.edu)

**Comment by camiplata** [comment]
* 8 AM Colombia Time (Bogotá)

**Comment by baskaufs** [comment]
The notes from the 2022-06-27 TAG meeting have been posted at https://github.com/tdwg/tag/blob/master/meetings/2022-06-27-tag-meeting-notes.pdf
