### ISSUE TITLE
TAG bimonthly meeting 13 March 2023

### ISSUE THREAD

**Issue by baskaufs** [tdwg/tag#40]
The next regularly scheduled bi-monthly meeting of the Technical Architecture Group is scheduled for 2023-03-13 at 13:00 UTC. To see this in your local time, visit [this link](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Technical+Architecture+Group+%28TAG%29&iso=20230313T13&p1=1440&ah=1).

**Please note that this meeting occurs immediately following the change to Daylight Savings time in the North America but the change to summer time will not have occurred yet in Europe.** So for North American participants the time will be an hour later than the previous meetings. Daylight Savings time will not yet have ended in Australia. **Verify your local time using the link above.**  

This meeting is open to the public. For the Zoom link and a calendar invitation, please email [steve.baskauf@vanderbilt.edu](mailto:steve.baskauf@vanderbilt.edu).

**Comment by gkampmeier** [comment]
I think you mean 13 March 2023...

**Comment by baskaufs** [comment]
@gkampmeier Thank you! It's fixed

**Comment by baskaufs** [comment]
The notes for the 2023-03-13 TAG meeting have been uploaded to https://github.com/tdwg/tag/blob/master/meetings/2023-03-13-tag-meeting-notes.pdf
