### ISSUE TITLE
Typo in Humboldt Core (ID vs. IRI terms) section?

### ISSUE THREAD

**Issue by ymgan** [tdwg/tag#41]
https://github.com/tdwg/tag/blob/7e126d7b0f0be78e17216c7084c28393f520a0e7/complex_values/use_cases.md?plain=1#L147

Thanks for writing this up @baskaufs! It is coherent with what I understood in the meeting :) I think there is a small typo in the paragraph 

> Thus the "ID" terms might be used instead (`dwc:samplingPerformedByID` and `dwciri:identifiedBy`)

Perhaps you meant `dwc:identifiedByID`? (unless I am mistaken) Thanks again!

**Comment by baskaufs** [comment]
Thanks for catching this, @ymgan ! I've fixed it.
Steve
