### ISSUE TITLE
Confirm membership

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#5]
-  Review Charter, 
- Review work plan,
- Agree milestones

**Comment by ghwhitbread** [comment]
Add collaborators from Tuesday's meeting, if they choose to accept:
@jar398
@dagendresen
@xjsachs
@pbuttigieg
Jeff Gerbracht (on github?)
Dimitris is already here.

**Comment by dagendresen** [comment]
Confirming membership - Dag

**Comment by stanblum** [comment]
Confirming membership - Stan

**Comment by jar398** [comment]
Confirming membership - Jonathan (@jar398)

**Comment by pbuttigieg** [comment]
Confirmed. - Pier

**Comment by WUlate** [comment]
Confirm membership.  -William

Sent from Yahoo Mail for iPhone


On Monday, October 2, 2017, 7:24 PM, Paul J. Morris <notifications@github.com> wrote:


Confirming membership. -Paul

**Comment by jgerbracht** [comment]
Confirming membership - Jeff

**Comment by baskaufs** [comment]
This issue is out of date and no longer relevant.
