### ISSUE TITLE
Revision of guid-as

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#7]
[guid-as](https://github.com/tdwg/guid-as/blob/master/guid/applicability_statement.doc)

* review implementation recommendations and principles
* revise recommended GUID lists
* update meta-data serialization specification ( currently RDF+XML, XML)

**Comment by baskaufs** [comment]
This effectively duplicates #9, which contains more extensive discussion and opinions on the topic. I am therefore closing this as a duplication.
