### ISSUE TITLE
Deprecate lsid-as document

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#8]
From #2 
Deprecate [lsid-as](https://github.com/tdwg/guid-as/blob/master/lsid/applicability_statement.doc)

* Remove from guid-as
* Annotate as deprecated
* Incorporate principles into guid-as ((authority, namespace, identifier), GET meta-data)

**Comment by baskaufs** [comment]
This duplicates #2 and the comments made here have already been tranferred to it.
